from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text, Float
from sqlalchemy.orm import relationship
from datetime import datetime, timedelta
from app.core.database import Base
from app.core.config import settings


class CallLog(Base):
    __tablename__ = "call_logs"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)

    # Call metrics
    duration = Column(Float, nullable=True)  # Duration in seconds
    status = Column(String(50), nullable=False)  # completed, failed, no-answer, busy, etc.

    # Full transcript
    transcript = Column(Text, nullable=True)

    # Summary (optional, generated by LLM)
    summary = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # GDPR: Retention policy
    retention_until = Column(
        DateTime,
        default=lambda: datetime.utcnow() + timedelta(days=settings.DATA_RETENTION_DAYS),
        nullable=False
    )

    # Relationships
    conversation = relationship("Conversation", back_populates="call_log")
